#:schema node_modules/wrangler/config-schema.json
name = "platform-notification"
main = "src/index.ts"
compatibility_date = "2025-01-24"

[[queues.consumers]]
queue = "client-notifications"
max_batch_size = 10
max_batch_timeout = 5

[[d1_databases]]
binding = "DB"
database_name = "pluto"
database_id = "c364bad3-ca8f-491b-9432-add0f8334dcf"
